---
title: "P8130 Final Project"
author: "Pengyuan Su (ps3195), Shuhong Xiang (sx2289), Yali Zhai (yz3959), Zhixing Wu (zw2709)"
date: "12/6/2020"
output: github_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(viridis)
library(purrr)

knitr::opts_chunk$set(
	echo = TRUE,
	warning = FALSE,
	fig.width = 8, 
  fig.height = 6,
  out.width = "90%"
)
options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)
scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
theme_set(theme_minimal() + theme(legend.position = "bottom"))
```


```{r load_libraries}
library(tidyverse)
library(modelr)
library(arsenal)
library(broom)
library(modelr)
library(patchwork)
library(mgcv)
library(faraway)
```

# Introduction



# Abstract 



# Data Analysis


## Tidy:

`rate`: hate_crimes_per_100k_splc

`med_income`: median_household_income

`high_degree`: perc_population_with_high_school_degree

`non_citizen`: perc_non_citizen

`non_white`: perc_non_white


```{r import data}
hc_df = 
  read_csv(here::here("data/HateCrimes.csv")) %>% 
  janitor::clean_names() %>% 
  mutate(hate_crimes_per_100k_splc = as.numeric(hate_crimes_per_100k_splc)) %>% 
  drop_na() %>% 
  rename(., 
         rate = hate_crimes_per_100k_splc, 
         med_income = median_household_income, 
         high_degree = perc_population_with_high_school_degree, 
         non_citizen = perc_non_citizen, 
         non_white = perc_non_white)

head(hc_df)
```

Description by table?

```{r}
my_controls <- tableby.control(
               total = T, # do you wanna show he overall col?
               test=F,  # No test p-values yet
               numeric.stats = c("meansd", "medianq1q3", "range", "Nmiss2"), # for the continuous var. (a.k.a numeric var.) 
               cat.stats = c("countpct", "Nmiss2"), # for categorical var., we select the count, percentage, and missing values.
               stats.labels = list(
               meansd = "Mean (SD)",
               medianq1q3 = "Median (Q1, Q3)",
               range = "Min - Max",
               Nmiss2 = "Missing",
               countpct = "N (%)"))





#summary(tab1, title = "Descriptive statistics ", text = T,  digits = 1) %>%  knitr::kable()   
```



## Plot distribution of hate crimes rate

```{r plot distribution of rate}
hc_df %>% 
  ggplot(aes(x = rate, y = ..density..)) +
  geom_histogram(fill = "blue", alpha = .4) +
  geom_density(aes( x = rate, y = ..density..)) +
  theme_bw() +
  labs(title = "Distribution for hate crimes per 100k",
       x = "hate crimes per 100k splc",
       y = " Count") +
  theme(plot.title = element_text(hjust = .5 ))


hc_df %>% 
  mutate(lg = log(rate)) %>% 
  ggplot(aes(x = lg, y = ..density..)) +
  geom_histogram(fill = "blue", alpha = .4) +
  geom_density(aes( lg, y = ..density..)) +
  theme_bw() +
  labs(title = "Distribution for Log ",
       x = "Log (hate crimes per 100k splc)",
       y = " Count") +
  theme(plot.title = element_text(hjust = .5 ))


```

## Verify association

**income**

```{r}
income = 
 lm(rate ~ med_income, data = hc_df)

summary(income)
```


**high school degree**

```{r}
degree = 
 lm(rate ~ high_degree, data = hc_df)

summary(degree)
```

**non citizen**

```{r}
noncitizen = 
 lm(rate ~ non_citizen, data = hc_df)

summary(noncitizen)
```


**non white**

```{r}
nonwhite = 
 lm(rate ~ non_white, data = hc_df)

summary(nonwhite)
```

**gini index**

```{r}
gini = 
 lm(rate ~ gini_index, data = hc_df)

summary(gini)
```

## MLR

```{r}
#mult.fit = lm(rate ~ ., data = hc_df)
#step(mult.fit, direction='backward')

#Error in step(mult.fit, direction = "backward") : 
  #AIC is -infinity for this model, so 'step' cannot proceed
```


